### PR TITLE
Sx10 set protection on

### PR DESCRIPTION
**Pull request by maggie-moheb**
@daliamaarek  @ahmad3m3  @AmirMaurice  @Youmna-Salah  please review :D #49

### CODE REVIEW

**Comment by AmirMaurice** [comment]
@maggie-moheb concerning the class diagram u need one for TvClicker not viewDevices, does this story have a wireframe ?

**Comment by AmirMaurice** [comment]
@maggie-moheb there are some errors in the test but not related to your story, your test runs successfully :+1:

**Comment by maggie-moheb** [comment]
@Youmna-Salah done :dancer:

**Comment by maggie-moheb** [comment]
@AmirMaurice  I removed the wrong class diagram
This story doesn't have wireframes or class diagrams because they are the same as the TV clicker class diagram and wireframes, please recheck

**Comment by AmirMaurice** [comment]
@maggie-moheb ok :smile: sequence diagram reviewed

**Comment by daliamaarek** [comment]
add yourself as an author in the class you documented

**Comment by maggie-moheb** [comment]
@Youmna-Salah & @AmirMaurice  please review again, test errors fixes

**Pull request merged**
