### PR TITLE
Sx31 hold on device for options

### PR DESCRIPTION
**Pull request by maggie-moheb**
@Youmna-Salah @daliamaarek @AmirMaurice @ahmad3m3  please review :D #51

### CODE REVIEW

**Comment by AmirMaurice** [comment]
@maggie-moheb  UML diagrams reviewed :+1:

**Comment by AmirMaurice** [comment]
@maggie-moheb test throws null pointer exception when calling renderViewNotes method, check it again

**Comment by daliamaarek** [comment]
instead of created by, write author
other than that, everything is perfect :+1:

**Comment by maggie-moheb** [comment]
@daliamaarek fixed :dancer:

**Comment by maggie-moheb** [comment]
@AmirMaurice  I tried it again and it is working fine on my PC

**Comment by maggie-moheb** [comment]
@Youmna-Salah  done :dancer:

**Comment by daliamaarek** [comment]
add yourself as an author in all the classes you documented

**Comment by maggie-moheb** [comment]
@daliamaarek done :dancer:

**Comment by AmirMaurice** [comment]
@maggie-moheb :+1:

**Pull request merged**
