### PR TITLE
Sx43 user can report problem

### PR DESCRIPTION
**Pull request by ahmad3m3**
@Youmna-Salah : kindly review the code, @AmirMaurice : kindly review the UML, @azamzamy check the documentation, @daliamaarek: please review the scenario.

### CODE REVIEW

**Comment by daliamaarek** [comment]
The "Report a problem by mail" button is on top of the "View By.." button

**Comment by AmirMaurice** [comment]
@ahmad3m3 I couldn't find ur test :cry:

**Comment by azamzamy** [comment]
@ahmad3m3 Good job.

**Comment by AmirMaurice** [comment]
@ahmad3m3 I think you have to specify which event will occur after user select by which application he will report the problem and where is the class diagram ?

**Comment by ahmad3m3** [comment]
@daliamaarek : When we merge the sidebar with this story we will get rid of those buttons 
@AmirMaurice : class diagram is added to the final class diagram please check it, regarding your first question the applications mentioned depends on the applications in the user's mobile.

**Comment by AmirMaurice** [comment]
@ahmad3m3 :+1:

**Pull request merged**
