### PR TITLE
Editing sx3 view rooms

### PR DESCRIPTION
**Pull request by AmirMaurice**
@maggie-moheb , @daliamaarek , @Youmna-Salah , @ahmad3m3  plz review :smile: 
#28

### CODE REVIEW

**Comment by daliamaarek** [comment]
In Rooms model class, you forgot to put write the params of the constructor. Other than that, everything is good :+1:

**Comment by AmirMaurice** [comment]
@daliamaarek  documentation added to Room constructor

**Comment by ahmad3m3** [comment]
@AmirMaurice : it works fine :+1:

**Comment by maggie-moheb** [comment]
please in the UML don't put the horizontal lines in the same level as there is difference in time

**Comment by maggie-moheb** [comment]
test is great :)

**Comment by AmirMaurice** [comment]
@maggie-moheb  plz check it again :smiley:

**Comment by maggie-moheb** [comment]
good job in the UML :)

**Pull request merged**
