### PR TITLE
Sx9 user can edit information

### PR DESCRIPTION
**Pull request by ahmad3m3**
#26 
@daliamaarek: kindly review the scenario , @maggie-moheb: kindly check the test  , @ahmad-diaa: kindly check the code  , @daliamaarek : kindly check the documentation.

### CODE REVIEW

**Comment by daliamaarek** [comment]
@ahmad3m3 Scenario works :balloon:

**Comment by daliamaarek** [comment]
@ahmad3m3 Please include documentation for setters and getters in changeInfo class

**Comment by daliamaarek** [comment]
@ahmad3m3 is changing password in this branch? If it is, don't forget to document pleeeease

**Comment by ahmad3m3** [comment]
Since I have been mistaken working on 2 user stories on a branch and branch from this branch, kindly review everything again for both user stories since both tests works now.
@daliamaarek: Scenario reviewing
@maggie-moheb: test reviewing 
@Youmna-Salah: Code reviewing 
@azamzamy: documentation reviewing

**Comment by maggie-moheb** [comment]
UML is great :)

**Comment by daliamaarek** [comment]
It works! (but in the inside the email textfield there's a "ya mosahel" written) :smile:

**Comment by ahmad3m3** [comment]
@Youmna-Salah : kindly re-check now.
@daliamaarek : I removed it :+1:

**Comment by ahmad3m3** [comment]
@Youmna-Salah : kindly re-check now.
@daliamaarek : it is now fixed :+1:

**Comment by ahmad3m3** [comment]
@Youmna-Salah : re-check please :pray:

**Comment by AmirMaurice** [comment]
@ahmad3m3  tests are fine :+1:

**Pull request merged**
