### PR TITLE
Sx28 adding clicker for each device

### PR DESCRIPTION
**Pull request by Youmna-Salah**

### CODE REVIEW

**Comment by Youmna-Salah** [comment]
@daliamaarek  @ahmad-diaa  @maggie-moheb  @ahmad3m3  @AmirMaurice

**Comment by AmirMaurice** [comment]
@Youmna-Salah :+1:

**Comment by maggie-moheb** [comment]
@Youmna-Salah test ran successfully :dancer:

**Comment by daliamaarek** [comment]
Documentation is great!

**Comment by Youmna-Salah** [comment]
@ahmad-diaa  done :smiley

**Comment by Youmna-Salah** [comment]
@ahmad-diaa :smiley:

**Comment by Youmna-Salah** [comment]
@ahmad-diaa  Done !! :smiley:

**Comment by Youmna-Salah** [comment]
@ahmad-diaa  Done :smiley:

**Pull request merged**
