### PR TITLE
SX30 context menu

### PR DESCRIPTION
**Pull request by azamzamy**
#29 
@daliamaarek: Documentation Reviewer
@ahmad-diaa: Code reviewer
@ahmad3m3: Scenario reviewer
@AmirMaurice : UML reviewer
@maggie-moheb: Dear Test Reviewer, No tests for this story, therefore no tests to be reviewed.

### CODE REVIEW

**Comment by AmirMaurice** [comment]
@azamzamy sequence diagram reviewed :+1:

**Comment by ahmad-diaa** [comment]
@azamzamy  
attributes have to be private (viewRooms.java)

**Comment by daliamaarek** [comment]
@azamzamy Documentation is good. :facepunch:

**Comment by azamzamy** [comment]
Done.

**Comment by ahmad-diaa** [comment]
@azamzamy :+1:

**Comment by ahmad3m3** [comment]
@azamzamy: It looks perfect, good job :+1:

**Comment by azamzamy** [comment]
@Youmna-Salah Deleted the blank space but after doing the auto identation, it reseparated some imports from the other and the blank space returned, so this is the default.

**Pull request merged**
