### PR TITLE
Sx20 user rename room

### PR DESCRIPTION
**Pull request by maggie-moheb**
@Youmna-Salah @daliamaarek  @ahmad3m3 @AmirMaurice please review my code
android: RenameRoomActivity, RenameRoomActivityTest
rails: rooms_controller, rooms_controller_test
UML_DIAGRAMS/rename room sequence diagram #17

### CODE REVIEW

**Comment by ahmad3m3** [comment]
@maggie-moheb : The Scenario works fine :+1:

**Comment by daliamaarek** [comment]
@maggie-moheb Documentation is great (yaaay!)

**Comment by AmirMaurice** [comment]
@maggie-moheb  good job :+1:

**Comment by AmirMaurice** [comment]
@maggie-moheb  tests reviewed

**Pull request merged**
