### PR TITLE
SX32 view by type

### PR DESCRIPTION
**Pull request by daliamaarek**
Hiii! 
@Youmna-Salah: code, @ahmad3m3: scenario, @maggie-moheb: test, @AmirMaurice: UML
Please and thank you!
:cookie: :cookie: :cookie:

### CODE REVIEW

**Comment by daliamaarek** [comment]
@Youmna-Salah gone! :cookie:

**Comment by AmirMaurice** [comment]
@daliamaarek in class diagram plz make sure that you write first the name of attribute then the type and add the parameters of methods, in sequence diagram plz specify that ViewRooms belongs to Android and make sure not to have arrows in the same level as there exits difference in time between them and a response back to the user is a must and finally I couldn't find ur wireframe

**Comment by daliamaarek** [comment]
@AmirMaurice I fixed the UMLs, please check again
I didn't add a wireframe because this issue is reopened just for minor adjustments, so it already has a wireframe.

**Comment by AmirMaurice** [comment]
@daliamaarek still the response back to the user is missed (List of devices of given type)

**Comment by daliamaarek** [comment]
@AmirMaurice Adjusted!

**Comment by AmirMaurice** [comment]
@daliamaarek  bravo dalia :cookie:

**Pull request merged**
