### PR TITLE
Sx28 user should add device controller for each device

### PR DESCRIPTION
**Pull request by Youmna-Salah**
@daliamaarek , @ahmad-diaa , @daliamaarek  , @maggie-moheb , @AmirMaurice  #24

### CODE REVIEW

**Comment by maggie-moheb** [comment]
Youmna please take another look at the test because it did not pass on my PC

**Comment by daliamaarek** [comment]
In the Clicker class, please write the author and purpose of the class as the first comment block,  document the constructor params. 
The Author needs to be written in the TVClickerActivity too.

**Comment by Youmna-Salah** [comment]
@maggie-moheb Kindly review the Test again :D

**Comment by Youmna-Salah** [comment]
@daliamaarek  :cookie: may you please recheck the documentation :smiley:

**Comment by daliamaarek** [comment]
In the clicker constuctor, you have to put each param in its own separate line, for example: 
params userID
params roomID
params deviceID
and in the beginning of each class, write "Purpose:" before the actual purpose 

Enjoy! :cookie:

**Comment by Youmna-Salah** [comment]
@daliamaarek  @ahmad-diaa  I have made some changes may you please review the code again :cookie: :smiley:

**Comment by Youmna-Salah** [comment]
@maggie-moheb  could you please recheck the test :smiley:

**Comment by maggie-moheb** [comment]
test is great now :)

**Comment by AmirMaurice** [comment]
@Youmna-Salah plz remove 0..* signs and reorder the sequence of events that happen

**Comment by Youmna-Salah** [comment]
@AmirMaurice kindly review the UML again :smiley:

**Comment by Youmna-Salah** [comment]
@daliamaarek  Kindly review the scenario again :cookie: :smiley:

**Comment by daliamaarek** [comment]
It works ;)

**Comment by AmirMaurice** [comment]
@Youmna-Salah, there exits a duplicate for the alt block "current clicker will be sent to android" in the middle between device controller and clicker controller. In the part of requesting the status of the selected device I guess  render TVClicker is missed between TVClickerActivity and user.

**Comment by Youmna-Salah** [comment]
@AmirMaurice Kindly review Tv clicker's UML :smiley:

**Comment by AmirMaurice** [comment]
@Youmna-Salah :+1:

**Comment by ahmad-diaa** [comment]
@Youmna-Salah  code reviewed

**Pull request closed without merging**
