### PR TITLE
Editing sx4 add device

### PR DESCRIPTION
**Pull request by AmirMaurice**
@daliamaarek , @ahmad-diaa , @ahmad3m3 , @maggie-moheb  plz review :grinning: 
#20

### CODE REVIEW

**Comment by ahmad3m3** [comment]
@AmirMaurice : it works fine

**Comment by maggie-moheb** [comment]
Test is great :+1:

**Comment by maggie-moheb** [comment]
please specify which controller in the server is actually dealing with this story in the UML

**Comment by daliamaarek** [comment]
please document the params in the device model class,

**Comment by AmirMaurice** [comment]
@Youmna-Salah  plz review addDevices, see it in the commit of documentation because there you will find the last version of this class.

**Comment by AmirMaurice** [comment]
@maggie-moheb I am already specifying the device controller "Device:rails controller"

**Comment by AmirMaurice** [comment]
@daliamaarek documentation added to Device constructor

**Comment by AmirMaurice** [comment]
@maggie-moheb  plz check sequence diagram again 
@ahmad-diaa commented code and extra spaces removed

**Comment by maggie-moheb** [comment]
good job in the UML :+1:

**Pull request merged**
