### PR TITLE
SX38_can_view_plugs

### PR DESCRIPTION
**Pull request by azamzamy**
#60

@ahmad-diaa 
@AmirMaurice 
@daliamaarek 
@ahmad3m3 
@maggie-moheb 
Other commits can be found in the linked issue :sweat_smile:

### CODE REVIEW

**Comment by azamzamy** [comment]
@ahmad-diaa Forgot to indent the test class :). Done

**Comment by maggie-moheb** [comment]
tests are great :+1:

**Comment by AmirMaurice** [comment]
@azamzamy plz specify explicitly what happens in the second part between android and rails in both direction

**Comment by azamzamy** [comment]
@AmirMaurice Done

**Comment by AmirMaurice** [comment]
@azamzamy :+1:

**Pull request merged**
