### PR TITLE
Sx12 delete device

### PR DESCRIPTION
**Pull request by daliamaarek**
#72

@ahmad-diaa: code, @azamzamy: documentation, @ahmad3m3: scenario, @maggie-moheb: test, @AmirMaurice: UML 

PLEASE! _puppy eyes_

### CODE REVIEW

**Comment by AmirMaurice** [comment]
@daliamaarek the confirmation of deletion has to be in ur sequence diagram and a response back to the user too

**Comment by maggie-moheb** [comment]
test is great :hamster:

**Comment by daliamaarek** [comment]
@AmirMaurice Done! :cake:

**Comment by AmirMaurice** [comment]
@daliamaarek what if the user doesn't confirm the deletion failure scenario has to be included in ur sequence diagram :see_no_evil:

**Comment by daliamaarek** [comment]
@AmirMaurice What about now? :cry: :crying_cat_face: :sob:

**Comment by AmirMaurice** [comment]
@daliamaarek :+1:

**Comment by azamzamy** [comment]
@daliamaarek Your documentation looks pretty good.

**Pull request merged**
