### PR TITLE
Editing sx19 add room

### PR DESCRIPTION
**Pull request by AmirMaurice**
@ahmad-diaa, @daliamaarek , @maggie-moheb plz review :smiley: 
#27

### CODE REVIEW

**Comment by ahmad3m3** [comment]
@AmirMaurice : it works fine

**Comment by AmirMaurice** [comment]
@ youmna review only class addRooms

**Comment by maggie-moheb** [comment]
UML is fine :)

**Comment by maggie-moheb** [comment]
Test is great :)

**Comment by maggie-moheb** [comment]
there is a problem in the horizontal lines in the uml please check it again. Sorry for the error

**Comment by daliamaarek** [comment]
documentation is great!

**Comment by AmirMaurice** [comment]
@maggie-moheb plz check sequence diagram again

**Comment by maggie-moheb** [comment]
sequence diagram is great :)

**Comment by daliamaarek** [comment]
Scenario is fine

**Comment by AmirMaurice** [comment]
@ahmad-diaa, in this branch I didn't modify addDevices at all, the commits related to addDevices exist only because the bug of AddDevices class so I deleted it and created addDevices with the same code instead :)

**Comment by ahmad-diaa** [comment]
ok, everything is good :+1:

**Pull request merged**
