### PR TITLE
Sx27 devices by type

### PR DESCRIPTION
**Pull request by daliamaarek**
Please review the deviceList class, UMLs, and tests :turtle: 
@Youmna-Salah @azamzamy @maggie-moheb @ahmad3m3 @AmirMaurice 
#21

### CODE REVIEW

**Comment by maggie-moheb** [comment]
test works fine :) :)

**Comment by AmirMaurice** [comment]
@daliamaarek  you have to specify an android entity to the right and you forgot about rails controllers

**Comment by AmirMaurice** [comment]
@daliamaarek  what I just said is concerning the sequence diagram

**Comment by daliamaarek** [comment]
@AmirMaurice I modified it, is there anything wrong with it?

**Comment by AmirMaurice** [comment]
@daliamaarek  you should specify explicitly  which class of android and which controller of rails for example Device: android and plz remove the 0..* from arrows and finally there exists a difference in the response between rails and android for example rails will response with json format but android will show types in spinner.

**Comment by daliamaarek** [comment]
@AmirMaurice Okay I get what you mean.. what about the current UML?

**Comment by AmirMaurice** [comment]
@daliamaarek great :+1:

**Comment by ahmad3m3** [comment]
@daliamaarek : It works fine

**Comment by azamzamy** [comment]
Documentation is great!

**Pull request merged**
