### PR TITLE
Sx8 user add note

### PR DESCRIPTION
**Pull request by maggie-moheb**
@Youmna-Salah @daliamaarek @AmirMaurice @ahmad3m3 please review the code and Sequence diagram #30 
android: AddNoteActivity, AddNoteActivityTest, ViewNotesActivity, ViewDeviceActivity
 rails: notes_controller, notes_controller_test
UML_DIAGRAMS/AddNoteActivity Sequence diagram

### CODE REVIEW

**Comment by daliamaarek** [comment]
@maggie-moheb In Android: 
AddNote: Please add the author to the first comment block, and add return and params in getters and setters. Add a method description for AddNote(View v) :cake:

**Comment by daliamaarek** [comment]
@maggie-moheb In Android:
AddNote: Please add the author to the first comment block, and add return and params in getters and setters. Add a method description for AddNote(View v) :cake:

**Comment by ahmad3m3** [comment]
@azamzamy : it works perfectly

**Comment by daliamaarek** [comment]
@maggie-moheb In ViewRoomsActivity, make sure that the comment blocks are added before the methods and that all params are defined. Add author and purpose blocks at the beginning of the class. Add return methods too

**Comment by daliamaarek** [comment]
@maggie-moheb In addNotes activity, just add the author and purpose

**Comment by daliamaarek** [comment]
@maggie-moheb 
Rails: Make sure that each comment starts with a capital letter and has correct punctuation.

**Comment by AmirMaurice** [comment]
@maggie-moheb tests and sequence diagram reviewed

**Comment by daliamaarek** [comment]
Documentation is awesome :hamburger:

**Pull request merged**
