### PR TITLE
Sx33 add device to favorites list

### PR DESCRIPTION
**Pull request by AmirMaurice**
@maggie-moheb, @Youmna-Salah, @daliamaarek, @ahmad3m3 kindly review :smile: 
#47

### CODE REVIEW

**Comment by AmirMaurice** [comment]
@youmna plz check it again :smiley:

**Comment by Youmna-Salah** [comment]
@AmirMaurice :+1:

**Comment by daliamaarek** [comment]
you should add yourself as an author in any class you added documentation to, and document the methods you added in myAPI

**Comment by maggie-moheb** [comment]
@AmirMaurice in the class diagram can you please put the 2 arrows of if true value and if false value on the same horizontal level? in time they happen at the same time

**Comment by maggie-moheb** [comment]
@AmirMaurice  tests are great :D

**Comment by AmirMaurice** [comment]
@maggie-moheb, @daliamaarek  plz review it again :smiley:

**Comment by daliamaarek** [comment]
add yourself as an author in myAPI too

**Comment by AmirMaurice** [comment]
@daliamaarek I added @author in myAPI :smiley:

**Comment by maggie-moheb** [comment]
:+1:

**Pull request merged**
